# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.checkout("ThreeJS")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("NetworkViz"); Pkg.test("NetworkViz"; coverage=true)'
